SELECT COALESCE(bi.isbn, ExtractValue(bm.metadata, '//datafield[@tag="010"]/subfield[@code="z"]')) AS "isbn",
    REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(i.stocknumber,"ӕ","ae"),"Ӕ","AE"),"ḍ","d"),"Ḍ","D"),"ƒ","f"),"Ḥ","H"),"ḵ","k"),"Ḵ","K"),"Œ","oe"),"œ","OE"),"ṭ","t"),"Ṭ","T"),"’","'"),"‚",","),"ā|ă|ą|ȧ|ǎ|ȁ|ȃ","a"),"Ā|Ă|Ą|Ȧ|Ǎ|Ȁ|Ȃ","A"),"ć|č","c"),"Ć|Č","C"),"ē|ẽ|ĕ|ę|ė|ě|ȅ|ȇ|€","e"),"Ē|Ẽ|Ĕ|Ę|Ė|Ě|Ȅ|Ȇ","E"),"ǥ|ġ|ǧ|ğ","g"),"Ǥ|Ġ|Ǧ|Ğ","G"),"ḥ|ẖ","h"),"ī|ị|ĩ|ĭ|į|ǐ|ȉ|ȋ","i"),"Ī|Ị|Ĩ|Ĭ|Į|Ǐ|Ȉ|Ȋ","I"),"ḷ|ḹ|ḻ","l"),"Ḷ|Ḹ|Ḻ","L"),"ṁ|ṃ","m"),"Ṁ|Ṃ","M"),"ṅ|ǹ|ń|ṉ|ṇ","n"),"Ṅ|Ǹ|Ń|Ṉ|Ṇ","N"),"ō|ǒ|ŏ|ǫ|ȯ|ő|ȍ|ȏ","o"),"Ō|Ǒ|Ŏ|Ǫ|Ȯ|Ő|Ȍ|Ȏ","O"),"ṛ|r̥|ṝ|ř|ṟ","r"),"Ṛ|R̥|Ṝ|Ř","R"),"ś|ṣ|ş|ş|š|ṡ","s"),"Ś|Ṣ|Ş|Š|Ṡ","S"),"ū|ũ|ŭ|ų|ű|ǔ|ȕ|ȗ","u"),"Ū|Ũ|Ŭ|Ų|Ű|Ǔ|Ȕ|Ȗ","U"),"ź|ẓ|ż","z"),"Ž|Ź|Ẓ|Ż","Z"),'”|“|…|\\.\\.\\.|«|»|\\"|\\(|\\)|\\[|\\]|\\?|:|&',"") AS "915$a",
    REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(i.barcode,"ӕ","ae"),"Ӕ","AE"),"ḍ","d"),"Ḍ","D"),"ƒ","f"),"Ḥ","H"),"ḵ","k"),"Ḵ","K"),"Œ","oe"),"œ","OE"),"ṭ","t"),"Ṭ","T"),"’","'"),"‚",","),"ā|ă|ą|ȧ|ǎ|ȁ|ȃ","a"),"Ā|Ă|Ą|Ȧ|Ǎ|Ȁ|Ȃ","A"),"ć|č","c"),"Ć|Č","C"),"ē|ẽ|ĕ|ę|ė|ě|ȅ|ȇ|€","e"),"Ē|Ẽ|Ĕ|Ę|Ė|Ě|Ȅ|Ȇ","E"),"ǥ|ġ|ǧ|ğ","g"),"Ǥ|Ġ|Ǧ|Ğ","G"),"ḥ|ẖ","h"),"ī|ị|ĩ|ĭ|į|ǐ|ȉ|ȋ","i"),"Ī|Ị|Ĩ|Ĭ|Į|Ǐ|Ȉ|Ȋ","I"),"ḷ|ḹ|ḻ","l"),"Ḷ|Ḹ|Ḻ","L"),"ṁ|ṃ","m"),"Ṁ|Ṃ","M"),"ṅ|ǹ|ń|ṉ|ṇ","n"),"Ṅ|Ǹ|Ń|Ṉ|Ṇ","N"),"ō|ǒ|ŏ|ǫ|ȯ|ő|ȍ|ȏ","o"),"Ō|Ǒ|Ŏ|Ǫ|Ȯ|Ő|Ȍ|Ȏ","O"),"ṛ|r̥|ṝ|ř|ṟ","r"),"Ṛ|R̥|Ṝ|Ř","R"),"ś|ṣ|ş|ş|š|ṡ","s"),"Ś|Ṣ|Ş|Š|Ṡ","S"),"ū|ũ|ŭ|ų|ű|ǔ|ȕ|ȗ","u"),"Ū|Ũ|Ŭ|Ų|Ű|Ǔ|Ȕ|Ȗ","U"),"ź|ẓ|ż","z"),"Ž|Ź|Ẓ|Ż","Z"),'”|“|…|\\.\\.\\.|«|»|\\"|\\(|\\)|\\[|\\]|\\?|:|&',"") AS "915$b",
    REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(i.location,"ӕ","ae"),"Ӕ","AE"),"ḍ","d"),"Ḍ","D"),"ƒ","f"),"Ḥ","H"),"ḵ","k"),"Ḵ","K"),"Œ","oe"),"œ","OE"),"ṭ","t"),"Ṭ","T"),"’","'"),"‚",","),"ā|ă|ą|ȧ|ǎ|ȁ|ȃ","a"),"Ā|Ă|Ą|Ȧ|Ǎ|Ȁ|Ȃ","A"),"ć|č","c"),"Ć|Č","C"),"ē|ẽ|ĕ|ę|ė|ě|ȅ|ȇ|€","e"),"Ē|Ẽ|Ĕ|Ę|Ė|Ě|Ȅ|Ȇ","E"),"ǥ|ġ|ǧ|ğ","g"),"Ǥ|Ġ|Ǧ|Ğ","G"),"ḥ|ẖ","h"),"ī|ị|ĩ|ĭ|į|ǐ|ȉ|ȋ","i"),"Ī|Ị|Ĩ|Ĭ|Į|Ǐ|Ȉ|Ȋ","I"),"ḷ|ḹ|ḻ","l"),"Ḷ|Ḹ|Ḻ","L"),"ṁ|ṃ","m"),"Ṁ|Ṃ","M"),"ṅ|ǹ|ń|ṉ|ṇ","n"),"Ṅ|Ǹ|Ń|Ṉ|Ṇ","N"),"ō|ǒ|ŏ|ǫ|ȯ|ő|ȍ|ȏ","o"),"Ō|Ǒ|Ŏ|Ǫ|Ȯ|Ő|Ȍ|Ȏ","O"),"ṛ|r̥|ṝ|ř|ṟ","r"),"Ṛ|R̥|Ṝ|Ř","R"),"ś|ṣ|ş|ş|š|ṡ","s"),"Ś|Ṣ|Ş|Š|Ṡ","S"),"ū|ũ|ŭ|ų|ű|ǔ|ȕ|ȗ","u"),"Ū|Ũ|Ŭ|Ų|Ű|Ǔ|Ȕ|Ȗ","U"),"ź|ẓ|ż","z"),"Ž|Ź|Ẓ|Ż","Z"),'”|“|…|\\.\\.\\.|«|»|\\"|\\(|\\)|\\[|\\]|\\?|:|&',"") AS "930$c",
    REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(i.ccode,"ӕ","ae"),"Ӕ","AE"),"ḍ","d"),"Ḍ","D"),"ƒ","f"),"Ḥ","H"),"ḵ","k"),"Ḵ","K"),"Œ","oe"),"œ","OE"),"ṭ","t"),"Ṭ","T"),"’","'"),"‚",","),"ā|ă|ą|ȧ|ǎ|ȁ|ȃ","a"),"Ā|Ă|Ą|Ȧ|Ǎ|Ȁ|Ȃ","A"),"ć|č","c"),"Ć|Č","C"),"ē|ẽ|ĕ|ę|ė|ě|ȅ|ȇ|€","e"),"Ē|Ẽ|Ĕ|Ę|Ė|Ě|Ȅ|Ȇ","E"),"ǥ|ġ|ǧ|ğ","g"),"Ǥ|Ġ|Ǧ|Ğ","G"),"ḥ|ẖ","h"),"ī|ị|ĩ|ĭ|į|ǐ|ȉ|ȋ","i"),"Ī|Ị|Ĩ|Ĭ|Į|Ǐ|Ȉ|Ȋ","I"),"ḷ|ḹ|ḻ","l"),"Ḷ|Ḹ|Ḻ","L"),"ṁ|ṃ","m"),"Ṁ|Ṃ","M"),"ṅ|ǹ|ń|ṉ|ṇ","n"),"Ṅ|Ǹ|Ń|Ṉ|Ṇ","N"),"ō|ǒ|ŏ|ǫ|ȯ|ő|ȍ|ȏ","o"),"Ō|Ǒ|Ŏ|Ǫ|Ȯ|Ő|Ȍ|Ȏ","O"),"ṛ|r̥|ṝ|ř|ṟ","r"),"Ṛ|R̥|Ṝ|Ř","R"),"ś|ṣ|ş|ş|š|ṡ","s"),"Ś|Ṣ|Ş|Š|Ṡ","S"),"ū|ũ|ŭ|ų|ű|ǔ|ȕ|ȗ","u"),"Ū|Ũ|Ŭ|Ų|Ű|Ǔ|Ȕ|Ȗ","U"),"ź|ẓ|ż","z"),"Ž|Ź|Ẓ|Ż","Z"),'”|“|…|\\.\\.\\.|«|»|\\"|\\(|\\)|\\[|\\]|\\?|:|&',"") AS "930$e",
    i.itemcallnumber AS "930$a",
    "g" AS "930$j",
    REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(i.enumchron,"ӕ","ae"),"Ӕ","AE"),"ḍ","d"),"Ḍ","D"),"ƒ","f"),"Ḥ","H"),"ḵ","k"),"Ḵ","K"),"Œ","oe"),"œ","OE"),"ṭ","t"),"Ṭ","T"),"’","'"),"‚",","),"ā|ă|ą|ȧ|ǎ|ȁ|ȃ","a"),"Ā|Ă|Ą|Ȧ|Ǎ|Ȁ|Ȃ","A"),"ć|č","c"),"Ć|Č","C"),"ē|ẽ|ĕ|ę|ė|ě|ȅ|ȇ|€","e"),"Ē|Ẽ|Ĕ|Ę|Ė|Ě|Ȅ|Ȇ","E"),"ǥ|ġ|ǧ|ğ","g"),"Ǥ|Ġ|Ǧ|Ğ","G"),"ḥ|ẖ","h"),"ī|ị|ĩ|ĭ|į|ǐ|ȉ|ȋ","i"),"Ī|Ị|Ĩ|Ĭ|Į|Ǐ|Ȉ|Ȋ","I"),"ḷ|ḹ|ḻ","l"),"Ḷ|Ḹ|Ḻ","L"),"ṁ|ṃ","m"),"Ṁ|Ṃ","M"),"ṅ|ǹ|ń|ṉ|ṇ","n"),"Ṅ|Ǹ|Ń|Ṉ|Ṇ","N"),"ō|ǒ|ŏ|ǫ|ȯ|ő|ȍ|ȏ","o"),"Ō|Ǒ|Ŏ|Ǫ|Ȯ|Ő|Ȍ|Ȏ","O"),"ṛ|r̥|ṝ|ř|ṟ","r"),"Ṛ|R̥|Ṝ|Ř","R"),"ś|ṣ|ş|ş|š|ṡ","s"),"Ś|Ṣ|Ş|Š|Ṡ","S"),"ū|ũ|ŭ|ų|ű|ǔ|ȕ|ȗ","u"),"Ū|Ũ|Ŭ|Ų|Ű|Ǔ|Ȕ|Ȗ","U"),"ź|ẓ|ż","z"),"Ž|Ź|Ẓ|Ż","Z"),'”|“|…|\\.\\.\\.|«|»|\\"|\\(|\\)|\\[|\\]|\\?|:|&',"") AS "930$v",
    biblionumber AS "L035$a"

FROM items i
LEFT JOIN biblioitems bi USING(biblionumber)
LEFT JOIN biblio b USING(biblionumber)
LEFT JOIN biblio_metadata bm USING(biblionumber)

WHERE bi.itemtype = <<Type de document|TYPEDOC>>
	AND i.notforloan NOT IN ("2", "6", "8")
    AND i.homebranch = <<École|branches>>
    AND i.itemlost != "1"
    AND i.withdrawn != "1"
    AND (
        ExtractValue(bm.metadata, '//datafield[@tag="010"]/subfield[@code="a"]') != ''
        OR ExtractValue(bm.metadata, '//datafield[@tag="010"]/subfield[@code="z"]') != ''
    )
    AND (
            b.abstract IS NULL 
            OR b.abstract = ""
        )

GROUP BY biblionumber

ORDER BY biblionumber asc

/* Ticket AR459 : variante du ID 1517 pour interroger les documents avec ISBn & sans PPN */